language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - python compile_cython.py
# command to run tests
script:
  - pytest