language: python
#dist: xenial
os:
#  - linux
  - osx
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - python compile_cython.py
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pytest